package entities;
// Generated Jan 6, 2019 2:57:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inspektor generated by hbm2java
 */
public class Inspektor  implements java.io.Serializable {


     private int insId;
     private PolicijskaStanica policijskaStanica;
     private String insIme;
     private String insPrezime;
     private Date insDtrodj;
     private String insTelefon;
     private String insAdresa;
     private String insKorisnickoIme;
     private String insSifra;

    public Inspektor() {
    }

	
    public Inspektor(int insId, String insIme, String insPrezime, String insKorisnickoIme, String insSifra) {
        this.insId = insId;
        this.insIme = insIme;
        this.insPrezime = insPrezime;
        this.insKorisnickoIme = insKorisnickoIme;
        this.insSifra = insSifra;
    }
    public Inspektor(int insId, PolicijskaStanica policijskaStanica, String insIme, String insPrezime, Date insDtrodj, String insTelefon, String insAdresa, String insKorisnickoIme, String insSifra) {
       this.insId = insId;
       this.policijskaStanica = policijskaStanica;
       this.insIme = insIme;
       this.insPrezime = insPrezime;
       this.insDtrodj = insDtrodj;
       this.insTelefon = insTelefon;
       this.insAdresa = insAdresa;
       this.insKorisnickoIme = insKorisnickoIme;
       this.insSifra = insSifra;
    }
   
    public int getInsId() {
        return this.insId;
    }
    
    public void setInsId(int insId) {
        this.insId = insId;
    }
    public PolicijskaStanica getPolicijskaStanica() {
        return this.policijskaStanica;
    }
    
    public void setPolicijskaStanica(PolicijskaStanica policijskaStanica) {
        this.policijskaStanica = policijskaStanica;
    }
    public String getInsIme() {
        return this.insIme;
    }
    
    public void setInsIme(String insIme) {
        this.insIme = insIme;
    }
    public String getInsPrezime() {
        return this.insPrezime;
    }
    
    public void setInsPrezime(String insPrezime) {
        this.insPrezime = insPrezime;
    }
    public Date getInsDtrodj() {
        return this.insDtrodj;
    }
    
    public void setInsDtrodj(Date insDtrodj) {
        this.insDtrodj = insDtrodj;
    }
    public String getInsTelefon() {
        return this.insTelefon;
    }
    
    public void setInsTelefon(String insTelefon) {
        this.insTelefon = insTelefon;
    }
    public String getInsAdresa() {
        return this.insAdresa;
    }
    
    public void setInsAdresa(String insAdresa) {
        this.insAdresa = insAdresa;
    }
    public String getInsKorisnickoIme() {
        return this.insKorisnickoIme;
    }
    
    public void setInsKorisnickoIme(String insKorisnickoIme) {
        this.insKorisnickoIme = insKorisnickoIme;
    }
    public String getInsSifra() {
        return this.insSifra;
    }
    
    public void setInsSifra(String insSifra) {
        this.insSifra = insSifra;
    }




}


