package entities;
// Generated Jan 6, 2019 2:57:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;

/**
 * KrivicnoDelo generated by hbm2java
 */
public class KrivicnoDelo  implements java.io.Serializable {

     private int kriId;
     private Date kriPocetak;
     private Date kriKraj;
     private Integer kriClan;
     private String kriOpis;
     
     private Set inspektori;
     private Set osteceni;
     private Set osumnjiceni;
     private Set svedoci;

    public KrivicnoDelo() {
    }

    public KrivicnoDelo(int kriId) {
        this.kriId = kriId;
    }
    
    public KrivicnoDelo(int kriId, Date kriPocetak, Date kriKraj, Integer kriClan, String kriOpis) {
       this.kriId = kriId;
       this.kriPocetak = kriPocetak;
       this.kriKraj = kriKraj;
       this.kriClan = kriClan;
       this.kriOpis = kriOpis;
    }

    public Set getOsteceni() {
        return osteceni;
    }

    public void setOsteceni(Set osteceni) {
        this.osteceni = osteceni;
    }

    public Set getOsumnjiceni() {
        return osumnjiceni;
    }

    public void setOsumnjiceni(Set osumnjiceni) {
        this.osumnjiceni = osumnjiceni;
    }

    public Set getSvedoci() {
        return svedoci;
    }

    public void setSvedoci(Set svedoci) {
        this.svedoci = svedoci;
    }
    
    public Set getInspektori() {
        return inspektori;
    }

    public void setInspektori(Set inspektori) {
        this.inspektori = inspektori;
    }
    
    public int getKriId() {
        return this.kriId;
    }
    
    public void setKriId(int kriId) {
        this.kriId = kriId;
    }
    public Date getKriPocetak() {
        return this.kriPocetak;
    }
    
    public void setKriPocetak(Date kriPocetak) {
        this.kriPocetak = kriPocetak;
    }
    public Date getKriKraj() {
        return this.kriKraj;
    }
    
    public void setKriKraj(Date kriKraj) {
        this.kriKraj = kriKraj;
    }
    public Integer getKriClan() {
        return this.kriClan;
    }
    
    public void setKriClan(Integer kriClan) {
        this.kriClan = kriClan;
    }
    public String getKriOpis() {
        return this.kriOpis;
    }
    
    public void setKriOpis(String kriOpis) {
        this.kriOpis = kriOpis;
    }




}


