package entities;
// Generated Jan 6, 2019 2:57:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nacelnik generated by hbm2java
 */
public class Nacelnik  implements java.io.Serializable {


     private int nacId;
     private String nacIme;
     private String nacPrezime;
     private Date nacDtrodj;
     private String nacTelefon;
     private String nacAdresa;
     private String nacKorisnickoIme;
     private String nacSifra;
     private Set policijskaStanicas = new HashSet(0);

    public Nacelnik() {
    }

	
    public Nacelnik(int nacId, String nacIme, String nacPrezime, String nacKorisnickoIme, String nacSifra) {
        this.nacId = nacId;
        this.nacIme = nacIme;
        this.nacPrezime = nacPrezime;
        this.nacKorisnickoIme = nacKorisnickoIme;
        this.nacSifra = nacSifra;
    }
    public Nacelnik(int nacId, String nacIme, String nacPrezime, Date nacDtrodj, String nacTelefon, String nacAdresa, String nacKorisnickoIme, String nacSifra, Set policijskaStanicas) {
       this.nacId = nacId;
       this.nacIme = nacIme;
       this.nacPrezime = nacPrezime;
       this.nacDtrodj = nacDtrodj;
       this.nacTelefon = nacTelefon;
       this.nacAdresa = nacAdresa;
       this.nacKorisnickoIme = nacKorisnickoIme;
       this.nacSifra = nacSifra;
       this.policijskaStanicas = policijskaStanicas;
    }
   
    public int getNacId() {
        return this.nacId;
    }
    
    public void setNacId(int nacId) {
        this.nacId = nacId;
    }
    public String getNacIme() {
        return this.nacIme;
    }
    
    public void setNacIme(String nacIme) {
        this.nacIme = nacIme;
    }
    public String getNacPrezime() {
        return this.nacPrezime;
    }
    
    public void setNacPrezime(String nacPrezime) {
        this.nacPrezime = nacPrezime;
    }
    public Date getNacDtrodj() {
        return this.nacDtrodj;
    }
    
    public void setNacDtrodj(Date nacDtrodj) {
        this.nacDtrodj = nacDtrodj;
    }
    public String getNacTelefon() {
        return this.nacTelefon;
    }
    
    public void setNacTelefon(String nacTelefon) {
        this.nacTelefon = nacTelefon;
    }
    public String getNacAdresa() {
        return this.nacAdresa;
    }
    
    public void setNacAdresa(String nacAdresa) {
        this.nacAdresa = nacAdresa;
    }
    public String getNacKorisnickoIme() {
        return this.nacKorisnickoIme;
    }
    
    public void setNacKorisnickoIme(String nacKorisnickoIme) {
        this.nacKorisnickoIme = nacKorisnickoIme;
    }
    public String getNacSifra() {
        return this.nacSifra;
    }
    
    public void setNacSifra(String nacSifra) {
        this.nacSifra = nacSifra;
    }
    public Set getPolicijskaStanicas() {
        return this.policijskaStanicas;
    }
    
    public void setPolicijskaStanicas(Set policijskaStanicas) {
        this.policijskaStanicas = policijskaStanicas;
    }




}


