package entities;
// Generated Jan 6, 2019 2:57:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Osteceni generated by hbm2java
 */
public class Osteceni  implements java.io.Serializable {


     private int ostId;
     private String ostIme;
     private String ostPrezime;
     private Date ostDtrodj;
     private String ostTelefon;
     private String ostAdresa;

    public Osteceni() {
    }

	
    public Osteceni(int ostId, String ostIme, String ostPrezime) {
        this.ostId = ostId;
        this.ostIme = ostIme;
        this.ostPrezime = ostPrezime;
    }
    public Osteceni(int ostId, String ostIme, String ostPrezime, Date ostDtrodj, String ostTelefon, String ostAdresa) {
       this.ostId = ostId;
       this.ostIme = ostIme;
       this.ostPrezime = ostPrezime;
       this.ostDtrodj = ostDtrodj;
       this.ostTelefon = ostTelefon;
       this.ostAdresa = ostAdresa;
    }
   
    public int getOstId() {
        return this.ostId;
    }
    
    public void setOstId(int ostId) {
        this.ostId = ostId;
    }
    public String getOstIme() {
        return this.ostIme;
    }
    
    public void setOstIme(String ostIme) {
        this.ostIme = ostIme;
    }
    public String getOstPrezime() {
        return this.ostPrezime;
    }
    
    public void setOstPrezime(String ostPrezime) {
        this.ostPrezime = ostPrezime;
    }
    public Date getOstDtrodj() {
        return this.ostDtrodj;
    }
    
    public void setOstDtrodj(Date ostDtrodj) {
        this.ostDtrodj = ostDtrodj;
    }
    public String getOstTelefon() {
        return this.ostTelefon;
    }
    
    public void setOstTelefon(String ostTelefon) {
        this.ostTelefon = ostTelefon;
    }
    public String getOstAdresa() {
        return this.ostAdresa;
    }
    
    public void setOstAdresa(String ostAdresa) {
        this.ostAdresa = ostAdresa;
    }




}


