package entities;
// Generated Jan 6, 2019 2:57:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Osumnjiceni generated by hbm2java
 */
public class Osumnjiceni  implements java.io.Serializable {


     private int osuId;
     private String osuIme;
     private String osuPrezime;
     private Date osuDtrodj;
     private String osuAdresa;
     private String osuTelefon;
     private Integer osuVisina;
     private Integer osuTezina;
     private String osuOpis;

    public Osumnjiceni() {
    }

	
    public Osumnjiceni(int osuId, String osuIme, String osuPrezime) {
        this.osuId = osuId;
        this.osuIme = osuIme;
        this.osuPrezime = osuPrezime;
    }
    public Osumnjiceni(int osuId, String osuIme, String osuPrezime, Date osuDtrodj, String osuAdresa, String osuTelefon, Integer osuVisina, Integer osuTezina, String osuOpis) {
       this.osuId = osuId;
       this.osuIme = osuIme;
       this.osuPrezime = osuPrezime;
       this.osuDtrodj = osuDtrodj;
       this.osuAdresa = osuAdresa;
       this.osuTelefon = osuTelefon;
       this.osuVisina = osuVisina;
       this.osuTezina = osuTezina;
       this.osuOpis = osuOpis;
    }
   
    public int getOsuId() {
        return this.osuId;
    }
    
    public void setOsuId(int osuId) {
        this.osuId = osuId;
    }
    public String getOsuIme() {
        return this.osuIme;
    }
    
    public void setOsuIme(String osuIme) {
        this.osuIme = osuIme;
    }
    public String getOsuPrezime() {
        return this.osuPrezime;
    }
    
    public void setOsuPrezime(String osuPrezime) {
        this.osuPrezime = osuPrezime;
    }
    public Date getOsuDtrodj() {
        return this.osuDtrodj;
    }
    
    public void setOsuDtrodj(Date osuDtrodj) {
        this.osuDtrodj = osuDtrodj;
    }
    public String getOsuAdresa() {
        return this.osuAdresa;
    }
    
    public void setOsuAdresa(String osuAdresa) {
        this.osuAdresa = osuAdresa;
    }
    public String getOsuTelefon() {
        return this.osuTelefon;
    }
    
    public void setOsuTelefon(String osuTelefon) {
        this.osuTelefon = osuTelefon;
    }
    public Integer getOsuVisina() {
        return this.osuVisina;
    }
    
    public void setOsuVisina(Integer osuVisina) {
        this.osuVisina = osuVisina;
    }
    public Integer getOsuTezina() {
        return this.osuTezina;
    }
    
    public void setOsuTezina(Integer osuTezina) {
        this.osuTezina = osuTezina;
    }
    public String getOsuOpis() {
        return this.osuOpis;
    }
    
    public void setOsuOpis(String osuOpis) {
        this.osuOpis = osuOpis;
    }




}


