package entities;
// Generated Jan 6, 2019 2:57:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PolicijskaStanica generated by hbm2java
 */
public class PolicijskaStanica  implements java.io.Serializable {


     private int polId;
     private Nacelnik nacelnik;
     private String polAdresa;
     private String polTelefon;
     private Set inspektors = new HashSet(0);

    public PolicijskaStanica() {
    }

	
    public PolicijskaStanica(int polId, Nacelnik nacelnik, String polAdresa, String polTelefon) {
        this.polId = polId;
        this.nacelnik = nacelnik;
        this.polAdresa = polAdresa;
        this.polTelefon = polTelefon;
    }
    public PolicijskaStanica(int polId, Nacelnik nacelnik, String polAdresa, String polTelefon, Set inspektors) {
       this.polId = polId;
       this.nacelnik = nacelnik;
       this.polAdresa = polAdresa;
       this.polTelefon = polTelefon;
       this.inspektors = inspektors;
    }
   
    public int getPolId() {
        return this.polId;
    }
    
    public void setPolId(int polId) {
        this.polId = polId;
    }
    public Nacelnik getNacelnik() {
        return this.nacelnik;
    }
    
    public void setNacelnik(Nacelnik nacelnik) {
        this.nacelnik = nacelnik;
    }
    public String getPolAdresa() {
        return this.polAdresa;
    }
    
    public void setPolAdresa(String polAdresa) {
        this.polAdresa = polAdresa;
    }
    public String getPolTelefon() {
        return this.polTelefon;
    }
    
    public void setPolTelefon(String polTelefon) {
        this.polTelefon = polTelefon;
    }
    public Set getInspektors() {
        return this.inspektors;
    }
    
    public void setInspektors(Set inspektors) {
        this.inspektors = inspektors;
    }




}


